### PR TITLE
Add go mod and Vault 1.4 support

### PR DESCRIPTION
**Pull request by leseb**
*Add a simple go module file to help pulling the libray into other
projects.

* Add support for vault lib as of 1.4.X.
The http header does not seem to be useful at the moment, so let's
report it. However, we use a blank identifier once called.

Closes: #47
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@adityadani and @saheienko please take a look. Thanks in advance.

**Review by adityadani — APPROVED** [review]

**Comment by adityadani** [comment]
@leseb Thanks for submitting a PR.

**Comment by leseb** [comment]
@adityadani thanks for the approval, is there anything missing to move forward?

**Review by saheienko — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
